name: drbooking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  google_fonts:
  flutter_spinkit:
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  line_icons: ^2.0.1
  syncfusion_flutter_barcodes: ^24.2.8
  calendar_date_picker2:
  flutter_otp_text_field: ^1.1.1
  lottie:
  google_maps_flutter:
  dart_jsonwebtoken: ^2.13.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations:
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  url_launcher: ^6.1.10
  crypto: ^3.0.3
  get:
  intl:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

