name: drbooking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_linkify: ^6.0.0
  google_fonts:
  flutter_spinkit:
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  line_icons: ^2.0.1
  syncfusion_flutter_barcodes: ^24.2.8
  calendar_date_picker2:
  flutter_otp_text_field: ^1.1.1
  lottie:
  google_maps_flutter:
  dart_jsonwebtoken: ^2.13.0
  cached_network_image: ^3.3.1
  flutter_staggered_animations:
  qr_flutter: ^4.1.0
  quickalert: ^1.1.0
  url_launcher: ^6.1.10
  crypto: ^3.0.3
  uni_links: ^0.5.1
  get:
  geolocator: ^10.1.0
  expandable_text: ^2.3.0
  flutter_svg:
  loading_animation_widget: ^1.2.1
  firebase_messaging: ^14.7.1
  flutter_launcher_icons: "^0.13.1"
  intl:
  image_picker:
  month_year_picker:
  dio:
  flutter: 
    sdk: flutter
  firebase_dynamic_links: ^5.4.8
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # andro

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

